name: Top Repositories

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  metrics:
    runs-on: ubuntu-latest

    steps:
      - name: Generate repository metrics
        uses: lowlighter/metrics@latest
        with:
          user: MikiDevAHM
          token: ${{ secrets.METRICS_TOKEN }}

          # IMPORTANTES 👇
          template: classic
          base: repositories

          config_timezone: Europe/Vienna
